---
sidebar: sidebar 
permalink: reference-storage-limits.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP ha limiti di configurazione dello storage per garantire operazioni affidabili. Per ottenere prestazioni ottimali, non configurare il sistema ai valori massimi. 
---
= Limiti di storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP ha limiti di configurazione dello storage per garantire operazioni affidabili. Per ottenere prestazioni ottimali, non configurare il sistema ai valori massimi.



== Capacità massima del sistema per licenza

La capacità massima del sistema per un sistema Cloud Volumes ONTAP è determinata dalla relativa licenza. La capacità massima del sistema include lo storage basato su disco e lo storage a oggetti utilizzato per il tiering dei dati. NetApp non supporta il superamento di questo limite.

In Azure, i limiti dei dischi impediscono di raggiungere il limite di capacità di 368 TIB utilizzando solo i dischi. In questi casi, è possibile raggiungere il limite di capacità di 368 TIB di https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["tiering dei dati inattivi sullo storage a oggetti"^]. Fare riferimento a. <<Limiti di capacità e dischi in base alle dimensioni delle macchine virtuali Azure,Limiti di capacità e dischi in base alle dimensioni delle macchine virtuali Azure>> per ulteriori dettagli.

[cols="30,70"]
|===
| Licenza | Capacità massima del sistema (dischi + storage a oggetti) 


| Esplora | 2 TIB (il tiering dei dati non è supportato con Explore) 


| Standard | 10 TIB 


| Premium | 368 TIB 


| BYOL | 368 TIB per licenza 
|===
.Per ha, il limite di capacità della licenza è per nodo o per l'intera coppia ha?
Il limite di capacità è per l'intera coppia ha. Non è per nodo. Ad esempio, se si utilizza la licenza Premium, è possibile avere fino a 368 TIB di capacità tra entrambi i nodi.

.Per un sistema ha in AWS, i dati mirrorati vengono conteggiati rispetto al limite di capacità?
No, non è così. I dati di una coppia ha AWS vengono sottoposti a mirroring sincrono tra i nodi in modo che siano disponibili in caso di guasto. Ad esempio, se si acquista un disco 8 TIB sul nodo A, Cloud Manager alloca anche un disco 8 TIB sul nodo B che viene utilizzato per i dati mirrorati. Sebbene sia stato eseguito il provisioning di 16 TIB di capacità, solo 8 TIB sono contati rispetto al limite di licenza.



== Limiti di aggregato e disco per Cloud Volumes ONTAP in AWS

In Cloud Volumes ONTAP 9.4, tutti i tipi di istanze EC2 possono raggiungere il limite di capacità di 368 TIB utilizzando solo lo storage EBS o utilizzando lo storage EBS e il tiering su S3 (sia a nodo singolo che ha).

[cols="3*"]
|===
| Storage fisico | Parametro | Limite 


.5+| *Aggregati e dischi* | Numero massimo di aggregati | 34 per configurazioni a nodo singolo 18 per nodo in una configurazione ha ^1^ 


| Dimensione massima dell'aggregato | 96 TIB di capacità raw ^2^ 


| Dischi per aggregato | 1-6 ^3^ 


| Dimensione massima del disco | 16 TIB 


| Numero massimo di dischi dati in tutti gli aggregati ^4^ | 34 per configurazioni a nodo singolo 31 per nodo in una configurazione ha 


| *Gruppi RAID* | Massimo per aggregato | 1 
|===
Note:

. Non è possibile creare 18 aggregati su entrambi i nodi in una coppia ha, in quanto ciò supererebbe il limite del disco dati.
. Il limite di capacità aggregata si basa sui dischi che compongono l'aggregato. Il limite non include lo storage a oggetti utilizzato per il tiering dei dati.
. Tutti i dischi di un aggregato devono avere le stesse dimensioni.
. Il limite dei dischi dati è specifico per i dischi che contengono dati utente. Il disco di boot e il disco root per ogni nodo non sono inclusi in questo limite.




== Limiti di aggregato e disco per Cloud Volumes ONTAP in Azure

[cols="3*"]
|===
| Storage fisico | Parametro | Limite 


.5+| *Aggregati e dischi* | Numero massimo di aggregati | Uguale al limite di dischi 


| Dimensione massima dell'aggregato | 200 TIB di capacità raw ^1^ 


| Dischi per aggregato | 1-12 ^2^ 


| Dimensione massima del disco | 32 TIB 


| Numero massimo di dischi dati in tutti gli aggregati ^3^ | Dipende dalle dimensioni della macchina virtuale. <<Limiti di capacità e dischi in base alle dimensioni delle macchine virtuali Azure,Vedere di seguito>>. 


| *Gruppi RAID* | Massimo per aggregato | 1 
|===
Note:

. Il limite di capacità aggregata si basa sui dischi che compongono l'aggregato. Il limite non include lo storage a oggetti utilizzato per il tiering dei dati.
. Tutti i dischi di un aggregato devono avere le stesse dimensioni.
. Il limite dei dischi dati è specifico per i dischi che contengono dati utente. Il disco di boot e il disco root per ogni nodo non sono inclusi in questo limite.




=== Limiti di capacità e dischi in base alle dimensioni delle macchine virtuali Azure

In Azure, i sistemi a nodo singolo possono utilizzare dischi gestiti HDD standard, dischi gestiti SSD standard e dischi gestiti SSD Premium, con un massimo di 32 TIB per disco. Il numero di dischi supportati varia in base alle dimensioni della macchina virtuale.

Le tabelle riportate di seguito mostrano la capacità massima del sistema in base alle dimensioni delle macchine virtuali con i soli dischi e con il tiering dei dischi e dei dati cold sullo storage a oggetti.

I limiti dei dischi sono indicati in base alle dimensioni delle macchine virtuali per le licenze Premium e BYOL solo perché non è possibile raggiungere i limiti dei dischi con le licenze Explore o Standard a causa dei limiti di capacità del sistema.



==== Nodo singolo con licenza Premium

[cols="14,20,31,33"]
|===
| Dimensione della macchina virtuale | Numero massimo di dischi per nodo | Capacità massima del sistema con i soli dischi | Capacità massima del sistema con dischi e tiering dei dati 


| DS3_v2 | 15 | 368 TIB | Tiering non supportato 


| DS4_v2 | 31 | 368 TIB | 368 TIB 


| DS5_v2 | 63 | 368 TIB | 368 TIB 


| DS13_v2 | 31 | 368 TIB | 368 TIB 


| DS14_v2 | 63 | 368 TIB | 368 TIB 
|===


==== Nodo singolo con una o più licenze BYOL


NOTE: Per alcuni tipi di macchine virtuali, sono necessarie diverse licenze BYOL per raggiungere la capacità massima di sistema indicata di seguito. Ad esempio, sono necessarie 6 licenze BYOL per raggiungere 2 PIB con DS5_v2.

[cols="10,18,18,18,18,18"]
|===
| Dimensione della macchina virtuale | Numero massimo di dischi per nodo 2+| Capacità massima del sistema con una licenza 2+| Capacità massima del sistema con più licenze 


2+|  | *Dischi da soli* | *Dischi + tiering dei dati* | *Dischi da soli* | *Dischi + tiering dei dati* 


| DS3_v2 | 15 | 368 TIB | Tiering non supportato | 480 TIB | Tiering non supportato 


| DS4_v2 | 31 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x ogni licenza 


| DS5_v2 | 63 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x ogni licenza 


| DS13_v2 | 31 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x ogni licenza 


| DS14_v2 | 63 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x ogni licenza 
|===


== Limiti di storage logico

[cols="22,22,56"]
|===
| Storage logico | Parametro | Limite 


| *Storage Virtual Machine (SVM)* | Numero massimo di Cloud Volumes ONTAP (coppia ha o nodo singolo) | Un SVM per il servizio dati e un SVM di destinazione utilizzati per il disaster recovery. È possibile attivare la SVM di destinazione per l'accesso ai dati in caso di interruzione della SVM di origine. ^1^ una SVM che serve dati copre l'intero sistema Cloud Volumes ONTAP (coppia ha o nodo singolo). 


.2+| *File* | Dimensione massima | 16 TIB 


| Massimo per volume | In base alle dimensioni del volume, fino a 2 miliardi 


| *Volumi FlexClone* | Profondità del clone gerarchico ^2^ | 499 


.3+| *Volumi FlexVol* | Massimo per nodo | 500 


| Dimensione minima | 20 MB 


| Dimensione massima | AWS: In base alle dimensioni dell'aggregato ^3^ Azure: 100 TIB 


| *Qtree* | Massimo per volume FlexVol | 4,995 


| *Copie Snapshot* | Massimo per volume FlexVol | 1,023 
|===
Note:

. Cloud Manager non fornisce alcun supporto di configurazione o orchestrazione per il disaster recovery SVM. Inoltre, non supporta attività correlate allo storage su una SVM aggiuntiva. Per il disaster recovery di SVM, è necessario utilizzare System Manager o CLI.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guida rapida alla preparazione del disaster recovery per SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guida di SVM Disaster Recovery Express"^]


. La profondità dei cloni gerarchici è la profondità massima di una gerarchia nidificata di volumi FlexClone che è possibile creare da un singolo volume FlexVol.
. Sono supportati meno di 100 TIB perché gli aggregati per questa configurazione sono limitati a 96 TIB di capacità _raw_.




== Limiti dello storage iSCSI

[cols="3*"]
|===
| Storage iSCSI | Parametro | Limite 


.4+| *LUN* | Massimo per nodo | 1,024 


| Numero massimo di mappe LUN | 1,024 


| Dimensione massima | 16 TIB 


| Massimo per volume | 512 


| *igroups* | Massimo per nodo | 256 


.2+| *Iniziatori* | Massimo per nodo | 512 


| Massimo per igroup | 128 


| *Sessioni iSCSI* | Massimo per nodo | 1,024 


.2+| *LIF* | Massimo per porta | 32 


| Massimo per portset | 32 


| *Portset* | Massimo per nodo | 256 
|===