---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, alarms, cloudwatch, giveback, govcloud, detaching, encryption, snapmanager, features 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni. 
---
= Limitazioni note
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni.



== Limitazioni generali

Le seguenti limitazioni si applicano a Cloud Volumes ONTAP in AWS e in Azure.



=== Numero massimo di operazioni di replica simultanee

Il numero massimo di trasferimenti simultanei di SnapMirror o SnapVault per Cloud Volumes ONTAP è 100 per nodo, indipendentemente dal tipo di istanza o di macchina.



=== Gli aggiornamenti software devono essere completati da Cloud Manager

Gli aggiornamenti di Cloud Volumes ONTAP devono essere completati da Cloud Manager. Non aggiornare Cloud Volumes ONTAP utilizzando Gestione di sistema o l'interfaccia CLI. In questo modo si può influire sulla stabilità del sistema.



=== La crittografia non è supportata sui dischi di avvio e root

Se è stata attivata un'opzione del provider cloud che crittografa automaticamente tutti i nuovi volumi o dischi, è necessario disattivare temporaneamente tale opzione durante l'implementazione di Cloud Volumes ONTAP. In caso contrario, l'implementazione di Cloud Volumes ONTAP non riuscirà. La crittografia non è supportata sui dischi di avvio e root del sistema Cloud Volumes ONTAP.



=== L'implementazione di Cloud Volumes ONTAP non deve essere modificata dalla console del provider di cloud

Le modifiche apportate a una configurazione Cloud Volumes ONTAP dalla console del provider di servizi cloud comportano una configurazione non supportata. Qualsiasi modifica apportata alle risorse Cloud Volumes ONTAP create e gestite da Cloud Manager può influire sulla stabilità del sistema e sulla capacità di gestione del sistema da parte di Cloud Manager.



=== I dischi e gli aggregati devono essere gestiti da Cloud Manager

Tutti i dischi e gli aggregati devono essere creati ed eliminati direttamente da Cloud Manager. Non eseguire queste azioni da un altro tool di gestione. In questo modo si può influire sulla stabilità del sistema, ostacolare la possibilità di aggiungere dischi in futuro e potenzialmente generare tariffe ridondanti per i provider di cloud.



=== Limitazione delle licenze SnapManager

Le licenze SnapManager per server sono supportate con Cloud Volumes ONTAP. Le licenze per sistema storage (suite SnapManager) non sono supportate.



=== Funzionalità ONTAP non supportate

Le seguenti funzioni non sono supportate con Cloud Volumes ONTAP:

* Deduplica inline a livello di aggregato
* Deduplica in background a livello aggregato
* Centro di manutenzione dei dischi
* Pulizia dei dischi
* Fibre Channel (FC)
* Pool di flash
* FlexCache
* Volumi infiniti
* Gruppi di interfacce
* Failover LIF Intranode
* MetroCluster
* Multi-tenancy (è supportata una sola SVM per il servizio dati)
* Crittografia dei volumi NetApp
* RAID4, RAID-DP, RAID-TEC (RAID0 supportato)
* Service Processor
* Conformità SnapLock e modalità aziendali (solo cloud WORM supportato)
* SnapMirror sincrono
* VLAN




== Limitazioni note in AWS

Le seguenti limitazioni note influiscono su Cloud Volumes ONTAP in AWS.



=== Falsi allarmi segnalati da Amazon CloudWatch

Cloud Volumes ONTAP non rilascia le CPU quando è inattivo, quindi Amazon CloudWatch può segnalare un elevato avviso di CPU per l'istanza EC2 perché rileva un utilizzo del 100%. È possibile ignorare questo allarme. Il comando ONTAP statistics (Statistiche CPU) visualizza l'utilizzo effettivo delle CPU.



=== Le coppie Cloud Volumes ONTAP ha non supportano il giveback immediato dello storage

Dopo il riavvio di un nodo, il partner deve sincronizzare i dati prima di poter restituire lo storage. Il tempo necessario per risincronizzare i dati dipende dalla quantità di dati scritti dai client mentre il nodo era inattivo e dalla velocità di scrittura dei dati durante il periodo di giveback.



=== Limitazioni dell'area geografica AWS GovCloud (USA)

* Cloud Manager deve essere implementato in un'area AWS GovCloud (USA) se si desidera avviare istanze di Cloud Volumes ONTAP in qualsiasi area AWS GovCloud (USA).
* Se implementato nell'area geografica AWS GovCloud (USA), Cloud Manager non è in grado di rilevare i cluster ONTAP in una configurazione NetApp Private Storage per Microsoft Azure o NetApp Private Storage per SoftLayer.




=== La rimozione e il ricollegamento dei volumi EBS non sono supportati

Non è possibile scollegare un volume EBS da un'istanza di Cloud Volumes ONTAP e ricollegarlo a un'altra istanza di Cloud Volumes ONTAP. È necessario utilizzare Cloud Manager per replicare i dati tra istanze.



=== Limitazioni della crittografia

* Lo spostamento del LUN non è supportato sui sistemi con crittografia Cloud Volumes ONTAP attivata.
* Cloud Volumes ONTAP invia le chiavi di crittografia ai responsabili delle chiavi anche per gli aggregati che non sono riusciti a creare.
+
È necessario eliminare manualmente le chiavi dai key manager.


