---
sidebar: sidebar 
permalink: reference-supported-configs.html 
keywords: ec2, instance, type, vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations 
summary: Cloud Volumes ONTAP è disponibile in diverse configurazioni in AWS e Azure. 
---
= Configurazioni supportate
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP è disponibile in AWS e Azure in due opzioni di prezzo: Pay-as-you-go e Bring Your Own License (BYOL). Per il pay-as-you-go, puoi scegliere tra tre configurazioni: Explore, Standard o Premium.



== Cloud Volumes ONTAP per AWS

In AWS, è possibile implementare Cloud Volumes ONTAP come singolo sistema o coppia ha.

[cols="h,d,d,d,d"]
|===
|  | Esplora | Standard | Premium | BYOL 


| Tipi di istanze EC2 | m4.xlange  a| 
* m4,2 x grande
* r4.xlange

 a| 
* c4.4xgrande
* c4.8xlarge
* m4,4xgrande
* r4,2 x grande

 a| 
* c4.4xgrande
* c4.8xlarge
* m4.xlange
* m4,2 x grande
* m4,4xgrande
* r4.xlange
* r4,2 x grande




| Storage sottostante 4+| SSD General purpose, SSD IOPS con provisioning, HDD ottimizzati per il throughput e HDD a freddo, fino a 16 TIB per disco 


| Capacità massima del sistema (dischi + storage a oggetti) | 2 TIB | 10 TIB | 368 TIB | 368 TIB per licenza 
|===
Note:

. Se si abilita il tiering dei dati, il limite di capacità di un sistema rimane invariato. Il limite di capacità include sia dischi che storage a oggetti.
. Il tiering dei dati è supportato con lo standard Cloud Volumes ONTAP, Premium e BYOL.
. Quando si sceglie un tipo di istanza EC2, è possibile specificare se si tratta di un'istanza condivisa o dedicata.
. Le migliori prestazioni di scrittura sono supportate quando si utilizzano SSD EBS con standard Cloud Volumes ONTAP, Premium e BYOL.
. Per il supporto della regione AWS, vedere https://cloud.netapp.com/cloud-volumes-global-regions["Cloud Volumes Global Regions"^].




== Cloud Volumes ONTAP per Azure

In Azure, è possibile implementare Cloud Volumes ONTAP come sistema a nodo singolo.

[cols="h,d,d,d,d"]
|===
|  | Esplora | Standard | Premium | BYOL 


| Tipi di macchine virtuali | DS3_v2  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2

 a| 
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2




| Storage sottostante 4+| Dischi gestiti HDD standard, dischi gestiti SSD standard e dischi gestiti SSD Premium, fino a 32 TIB per disco 


| Capacità massima del sistema (dischi + storage a oggetti) | 2 TIB | 10 TIB | 368 TIB | 368 TIB per licenza 
|===
Note:

. Se si abilita il tiering dei dati, il limite di capacità di un sistema rimane invariato. Il limite di capacità include sia dischi che storage a oggetti.
. Il tiering dei dati non è supportato con il tipo di macchina virtuale DS3_v2.
. Le migliori prestazioni di scrittura sono abilitate quando si utilizzano dischi Azure Premium Storage, ma non quando si utilizza il tipo di macchina virtuale DS3_v2.
. Per il supporto della regione Azure, vedere https://cloud.netapp.com/cloud-volumes-global-regions["Cloud Volumes Global Regions"^].

